tikv/community

sig/coprocessor/membership.md

My name is Zhuang Tianyi from Megvii. I first contribute to TiKV since around Aug, 2018.
I submit multiple PR to tikv:
* https://github.com/tikv/tikv/pull/3374
* https://github.com/tikv/tikv/pull/3870
* https://github.com/tikv/tikv/pull/5866 (A medium PCP task)
This PR adds me to the list of coprocessor-sig active contributor. I have read and understand the expectations of active contributor described in the https://github.com/tikv/community/blob/master/sig/coprocessor/constitution-zh_CN.md.

Add @TennyZhuang to coprocessor-sig active contributor

---

sig/coprocessor/membership.md

Signed-off-by: Lonng <heng@lonng.org>
I nominated to promote  [@niedhui](https://github.com/niedhui) from active contributor to reviewer, as niedhui's contribution to tikv has reached the [reviewer's standard]( [@niedhui](https://github.com/niedhui)).
- Merged [35 PRs](https://github.com/tikv/tikv/pulls?q=is%3Apr+author%3Aniedhui+is%3Aclosed)
- https://github.com/tikv/tikv/pull/5725 (A High PCP task)

copr-sig: Promote `niedhui` from Active contributor to Reviewer

---

committee/README.md

Signed-off-by: winkyao <golangwink@gmail.com>
Referring to this article [http://oss-watch.ac.uk/resources/meritocraticgovernancemodel](http://oss-watch.ac.uk/resources/meritocraticgovernancemodel), we need to redefine our PMC list, so I will revert the previous list firstly.

PMC: remove unvoted PMC list

---

sig/coprocessor/membership.md

Signed-off-by: Zhu Zihao <all_but_last@163.com>
I am Zhu Zihao, an independent developer. Start contributing to TiKV since Nov 12, 2019.
I submit multipe PRs to the coprocessor component of TiKV.
PCP(Easy)
- https://github.com/tikv/tikv/pull/5872
- https://github.com/tikv/tikv/pull/5894
- https://github.com/tikv/tikv/pull/5899
- https://github.com/tikv/tikv/pull/5946
- https://github.com/tikv/tikv/pull/5978
- https://github.com/tikv/tikv/pull/6012
- https://github.com/tikv/tikv/pull/6109
- https://github.com/tikv/tikv/pull/6130
Bugfixes:
- https://github.com/tikv/tikv/pull/5999
- https://github.com/tikv/tikv/pull/6032
This PR adds me to the list of coprocessor-sig active contributor. I have read  following documents and understood the expectation of an active contributor.
- …

Add @cireu to coprocessor-sig active contributor.

---

sig/coprocessor/membership.md

Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
I'm Hetian Zhu, an opensource enthusiast. Start contributing to TiKV and its ecosystem since Dec 30, 2018. 
I've submitted multiple PRs to the coprocessor component of TiKV.
Relate PRs: 
- https://github.com/tikv/tikv/pull/6388
- https://github.com/tikv/tikv/pull/6315
- https://github.com/tikv/tikv/pull/6312
- https://github.com/tikv/copr-test/pull/11
- https://github.com/tikv/tikv/pull/5839
- https://github.com/tikv/copr-test/pull/9
- https://github.com/tikv/tikv/pull/5829
- https://github.com/tikv/tikv/pull/5812
This PR adds me to the list of coprocessor-sig active contributor. I have read following documents and understood the expectation of an active contributor.
https://github.com/tikv/community/blob/master/sig/coprocessor/workflow-z …

Add @Fullstop000 to coprocessor-sig active contributor

---

sig/coprocessor/membership.md

@TennyZhuang is a new star in Coprocessor SIG and very well known recently. He has notably drived many important projects, like:
- Greatly improved LIKE() performance: https://github.com/tikv/tikv/pull/5866
- Greatly improved IN() performance: https://github.com/tikv/tikv/pull/6000
- Refine TiDB's Time format to be 8 bytes as TiKV: https://github.com/tikv/tikv/pull/6418
He is also currently working on:
- Participant in implementing collation for TiKV: https://github.com/tikv/tikv/pull/6592
- Accept RPN expression to support complex expressions: https://github.com/tikv/tikv/pull/6313
- Implement the metadata framework: https://github.com/tikv/tikv/pull/5993
In addition, he also helped other contributors and reviewed several PRs for them. He is an expert on the Coprocessor module now. For …

Promote @TennyZhuang to Coprocessor Committer

---

sig/coprocessor/membership.md

My name is Ge Renkai from Fordeal. I first contribute to TiKV since around Aug, 2018.
I submit multiple PR to tikv:
* https://github.com/tikv/tikv/pull/6341
* https://github.com/tikv/tikv/pull/6163
* https://github.com/tikv/tikv/pull/5979
* https://github.com/tikv/rust-prometheus/pull/297
* https://github.com/tikv/rust-prometheus/pull/296
This PR adds me to the list of coprocessor-sig active contributor. I have read and understand the expectations of active contributor described in the https://github.com/tikv/community/blob/master/committee/sig-governance/SIG-GOVERNACE.md.

add member renkai

---

sig/coprocessor/membership.md

I am Yuning Zhang, a Computer Science student. I have been contributing to TiKV since April 2018.
I submit multiple PR to tikv:
- tikv/tikv#2914
- tikv/tikv#2928
- tikv/tikv#3115
- tikv/tikv#5856
- tikv/tikv#5861
- tikv/tikv#5863
- tikv/tikv#5864
- tikv/tikv#5885
- tikv/tikv#6968
and I am currently working on UCP tasks.
This PR adds me to the list of coprocessor-sig active contributors. I have read and understood the expectations of an active contributor described in the https://github.com/tikv/community/blob/master/sig/coprocessor/charter-zh_CN.md.

Add @codeworm96 to coprocessor-sig active contributor

---

sig/coprocessor/membership.md

I am Rustin Liu, a junior Software Development Engineer. I have been contributing to TiKV since Dec 2019.
I submit multiple PR to tikv:
- https://github.com/tikv/tikv/pull/6118
- https://github.com/tikv/tikv/pull/6117
- https://github.com/tikv/tikv/pull/6173
- https://github.com/tikv/tikv/pull/6288
- https://github.com/tikv/tikv/pull/6301
- https://github.com/tikv/tikv/pull/6287
- https://github.com/tikv/tikv/pull/8074
- https://github.com/tikv/tikv/pull/8096
This PR adds me to the list of coprocessor-sig active contributors. I have read and understood the expectations of an active contributor described in the https://github.com/tikv/community/blob/master/sig/coprocessor/charter-zh_CN.md.

Add @Rustin-Liu to coprocessor-sig active contributor

---

sig/coprocessor/membership.md

Changes:
1. @lonng is currently leading TiUP and other TiDB delivery affairs, so that he is stepped down as a Committer instead of Tech leader.
2. The Coprocessor SIG will be led by @SunRunAway and @lzmhhh123 comes from TiDB team in future so that TiDB and TiKV can better work together.  They will lead the Coprocessor SIG in the following 2 forms:
- Develop: Currently they are not familiar enough to the Coprocessor code base, so that they are in probation stage. They will follow the same way as other contributors, i.e. from active contributor -> reviewer -> committer. The probation stage ends when they are qualified to be a committer. We hope this transition can finish by the end of Q3.
- Manage: Starting from now, they will deeply participant in planning, designing, growing and operating …

A transition for Coprocessor SIG leadership

---

sig/engine/membership.md

According to sig-engine constitution, @tabokie meets the requirement to promote to reviewer by has >= 10 PRs merged:
https://github.com/tikv/tikv/pulls?q=is%3Apr+author%3Atabokie+is%3Aclosed+is%3Amerged
https://github.com/tikv/titan/pulls?q=is%3Apr+author%3Atabokie+is%3Aclosed+is%3Amerged
he also meets the requirement to promote to committer by finishing one important feature (Titan GC improvement):
https://github.com/tikv/titan/pull/121
Propose to promote him to sig-engine committer.
Signed-off-by: Yi Wu <yiwu@pingcap.com>

add tabokie (Xinye Tao) as sig-engine committer

---

sig/coprocessor/membership.md

I'm Alex Chi, an undergraduate student studying Computer Science. I've been contributing to TiKV since April 2020.
I have submitted multiple PRs to TiKV:
- https://github.com/tikv/tikv/pull/7767
- https://github.com/tikv/tikv/pull/7979
- https://github.com/tikv/tikv/pull/8019
- https://github.com/tikv/tikv/pull/8070
- https://github.com/tikv/tikv/pull/8125
- https://github.com/tikv/tikv/pull/8141
- https://github.com/tikv/tikv/pull/8152
- https://github.com/tikv/tikv/pull/8189
I'm currently working on Full Chunk-based Computing.
This PR adds me to the list of coprocessor-sig active contributors. I have read and understood the expectations of an active contributor described in the https://github.com/tikv/community/blob/master/sig/coprocessor/charter-zh_CN.md.

Add @skyzh to coprocessor-sig active contributor

---

sig/coprocessor/membership.md

@skyzh is the most talented contributor I have seen so far in the Coprocessor SIG. This PR promotes him directly from Active Contributor to Committer in the Coprocessor SIG for his impressive and outstanding contribution for the [Full Chunk based computing](https://github.com/tikv/tikv/issues/7724) task, which is also a CNCF CommunityBridge project.
Highlights:
- A huge refactor (5000+ LOC) with a well-organized and incremental style of change, PR by PR, reveals good understanding of the whole architecture and technical details.
- Almost in the right and nice direction all the time -- I left only very few comments to request for change for his refactoring work.
[A list of all PRs he has worked with](https://github.com/tikv/tikv/pulls?q=is%3Apr+author%3Askyzh).

Promote @skyzh to Coprocessor committer

---

sig/scheduling/README.md
sig/scheduling/constitution-zh_CN.md
sig/scheduling/constitution.md
sig/scheduling/membership.md

This PR is going to migrate scheduling SIG from PingCAP to TiKV.

sig: migrate scheduling SIG from PingCAP to TiKV

---

sig/raft/membership.md

@accelsao ported datadriven tests from cockroachdb and also did many
works about joint-consensus.
Signed-off-by: qupeng <qupeng@pingcap.com>

add one new reviews for raft sig.

---

sig/scheduling/membership.md

@howardlau1999 has done a lot of work for auto scaling and we are going to promote him as a reviewer. His mainly work includes:
- help finish the implementation of auto scaling in pd and tidb-operator
- refine the log format
- fix several bugs
All his work can be found in [pd](https://github.com/tikv/pd/pulls?q=is%3Apr+author%3Ahowardlau1999+is%3Aclosed) and [tidb-operator](https://github.com/pingcap/tidb-operator/pulls/howardlau1999).

sig-scheduling: promote howardlau1999 to reviewer

---

sig/coprocessor/membership.json

@skyzh is now the de facto Coprocessor leader, who leads the development, mentoring and reviewing happens in Coprocessor
This PR promotes him to the co-leader.

Promote skyzh to coLeader

---

sig/engine/membership.json

According to sig-engine constitution, @hunterlxt meets the requirement to promote to reviewer by has >= 10 PRs merged:
tikv repo:
rust-rocksdb repo:
Also he also meets the requirement to promote to committer by fixing a critical bug:
Propose to promote him to sig-engine committer.

Add hunterlxt (Xintao Liu) as sig-engine committer

---

sig/transaction/membership.json

@you06 has contributed a lot to [tipocket](https://github.com/pingcap/tipocket), which is a test framework inspired by jespen. So we would like to promote him to the transaction sig reviewer.
The other detailed contribution list:
- https://github.com/pingcap/tidb/pull/20755
- https://github.com/pingcap/tidb/pull/20159
- https://github.com/pingcap/tidb/pull/19220

transaction: Promote @you06 to reviewer

---

sig/coprocessor/membership.json

@Xuanwo is the mentee for [2020 Q3-Q4 CNCF Community Bridge](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q3-q4/selected_projects.md) project. In past two months, he added [ENUM / SET support](https://github.com/tikv/tikv/issues/8605) for coprocessor.
Here is a list of PRs he has worked on for the Community Bridge project.
* https://github.com/tikv/tikv/pull/8728
* https://github.com/tikv/tikv/pull/8740
* https://github.com/tikv/tikv/pull/8849
* https://github.com/tikv/tikv/pull/8948
* https://github.com/tikv/tikv/pull/8951
* https://github.com/tikv/tikv/pull/8988
* https://github.com/tikv/tikv/pull/9021
* https://github.com/tikv/tikv/pull/9133
* https://github.com/tikv/tikv/pull/9135
* https://github.com/tikv/tikv/pull/9143
* https://github.com/tikv/tikv/pull/9146
* …

Promote @Xuanwo to sig-copr reviewer

---

sig/transaction/membership.json

Zyguan has raised many issues(50+) for TiDB transaction and execution layer and made great contributions to the transaction test utilities like [jepsen](https://github.com/PingCAP-QE/jepsen) tests, tipocket, [tp-test](https://github.com/zyguan/go-randgen/tree/tp-test/tp-test), etc.
So we would like to promote him to the transaction sig reviewer.

Make zyguan reviewer for sig-transaction

---

sig/coprocessor/membership.json

Signed-off-by: Alex Chi <iskyzh@gmail.com>
@wangggong has been actively contributed to TiKV coprocessor since September, 2020. Here is a list of PR they have been worked with, including vectorizing date-time-related functions and string-related functions.
https://github.com/tikv/tikv/pulls?q=is%3Apr+author%3Awangggong
* https://github.com/tikv/tikv/pull/8144
* https://github.com/tikv/tikv/pull/8192
* https://github.com/tikv/tikv/pull/8999
* https://github.com/tikv/tikv/pull/9065
* https://github.com/tikv/tikv/pull/9085
* https://github.com/tikv/tikv/pull/9087
* https://github.com/tikv/tikv/pull/9141
* https://github.com/tikv/tikv/pull/9238
* https://github.com/tikv/tikv/pull/9370
* https://github.com/tikv/tikv/pull/9474
Therefore, I would like to promote @wangggong as active contributor.

Promote @wangggong to sig-copr active contributor

---

sig/coprocessor/membership.json

@wjhuang2016 and @lzmhhh123 is now in charge of reviewing code changes that ported from TiDB executor. Although they do not have enough contributions, I think they are eligible for reviewing new codes.

Add some TiDB executor committers as Coprocessor reviewer

---

sig/coprocessor/membership.json

@Jibbow is the mentee for [LFX Mentorship 2021 Spring](https://github.com/cncf/mentoring/blob/master/lfx-mentorship/2021/01-Spring/README.md). He added [coprocessor plugin support](https://github.com/tikv/tikv/issues/8036) (or so-called coprocessor v2) to TiKV. 
Prior to the mentorship, Andreas takes an active part in TiKV community and added a lot of operators for TiKV coprocessor. One of the most notable contributions is adding [variance function support](https://github.com/tikv/tikv/pull/9642) to TiKV coprocessor, which is [a long-missing piece](https://github.com/tikv/tikv/issues/4822) among push-down aggregation operators. <del>(Looking for someone integrating this with TiDB push-down plan later.)</del>
* https://github.com/tikv/tikv/pull/9634
* https://github.com/tikv/tikv/pull/9635 …

coprocessor: add Jibbow to Coprocessor reviewer

---

teams/tikv/team.json
votes/0141-gozssky-as-tikv-reviewer.md

vote: gozssky as TiKV reviwer

---

teams/tikv/team.json
votes/0179-move-match-template.md

Move match_template from TiKV components to an independent crate under TiKV org, and publish it to crates.io.
Closes https://github.com/tikv/community/issues/181

move match_template to tikv org

---

teams/tikv/team.json

Signed-off-by: JmPotato <ghzpotato@gmail.com>
Although #188 voted for JmPotato's promotion, we did not add him to TiKV's reviewer list. This PR fixes this.

Update the TiKV reviewer list to add JmPotato

---

votes/0197-SpadeA-Tang-as-tikv-committer.md

[@SpadeA-Tang](https://github.com/SpadeA-Tang) has continuously contributed to `tikv/tikv` on different components, including but not limited to storage, raftstore and related components.

vote for SpadeA-Tang as committer
