tikv/community

- README.md
> readme: fix a link

- sig/coprocessor/README.md
Signed-off-by: winkyao <golangwink@gmail.com>
Refine copr-sig README, add regular meeting time and contact information.
@lonng @breeswish PTAL
> sig/copr: refine README.md

- README.md
- sig-governace/SIG-GOVERNACE-zh_CN.md
Signed-off-by: winkyao <golangwink@gmail.com>
add governance session in README, working group governance is working in progress.
> README: add governance session

- sig/engine/README.md
- sig/engine/constitution-zh_CN.md
- sig/engine/membership.md
- sig/engine/workflow-zh_CN.md
This PR add coprocessor workflow and SIG constitution.
> sig/engine: Initial documents, in Chinese

- .github/CODEOWNERS
add codeowners for master branch
> .github: add codeowners

- committee/README.md
Signed-off-by: Calvin Weng <wenghao@pingcap.com>
> update more details for PMC

- committee/sig-governace/SIG-GOVERNACE.md
Signed-off-by: notginger <zhangyanqing@pingcap.com>
> fix format

- sig/coprocessor/membership.md
Contribution:
* Merged [8PRs](https://github.com/tikv/tikv/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3ATennyZhuang)
* https://github.com/tikv/tikv/pull/6000 (A medium PCP task)
* https://github.com/tikv/tikv/pull/5866 (A medium PCP task)
> copr-sig: Promote 'TennyZhuang' from Active contributor to Reviewer

- wg/multiple-dc-enhancemant/README.md
Signed-off-by: qupeng <qupeng@pingcap.com>
> add multiple-dc-enhancemant wg

- committee/wg-governance/wg-governance.md
Signed-off-by: notginger <zhangyanqing@pingcap.com>
> update wg governance

- sig/engine/membership.md
Signed-off-by: fredchenbj <cfworking@163.com>
I am Fu Chen,  start contributing to TiKV since Jan 24, 2018.
I have submitted multiple PRs related to the engine component of TiKV.
tikv pr:
- https://github.com/tikv/tikv/pull/4110
- https://github.com/tikv/tikv/pull/4222
- https://github.com/tikv/tikv/pull/4335
- https://github.com/tikv/tikv/pull/4383
- https://github.com/tikv/tikv/pull/4442
- https://github.com/tikv/tikv/pull/4486
- https://github.com/tikv/tikv/pull/4628
rust-rocksdb pr:
- https://github.com/tikv/rust-rocksdb/pull/227
- https://github.com/tikv/rust-rocksdb/pull/401
- https://github.com/tikv/rust-rocksdb/pull/402
- https://github.com/tikv/rust-rocksdb/pull/403
This PR adds me to the list of engine-sig reviewer. I have read the following documents and understood the …
> Add @fredchenbj to engine-sig reviewer

- sig/coprocessor/membership.md
@niedhui contributed more than 40 PRs in TiKV, mainly for the Coprocessor component: https://github.com/tikv/tikv/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aniedhui+
Besides implementing a lot of built-in functions, he has also implemented several important TiKV coprocessor features:
- https://github.com/tikv/tikv/pull/4454
- https://github.com/tikv/tikv/pull/5259
- https://github.com/tikv/tikv/pull/5323
- https://github.com/tikv/tikv/pull/5450
- https://github.com/tikv/tikv/pull/5496
- https://github.com/tikv/tikv/pull/5520
- https://github.com/tikv/tikv/pull/5725
- https://github.com/tikv/tikv/pull/6132
He has revealed great understanding for the Coprocessor module according to these PRs. He has also [helped reviewed many community …
> Promote @niedhui to committer

- sig/coprocessor/membership.md
@FullStop000 successfully finished several medium and even **HARD LEVEL** coprocessor tasks, as below:
- Make JSON Chunk compatible: https://github.com/tikv/tikv/pull/6388
- Make Decimal Chunk compatible: https://github.com/tikv/tikv/pull/6312
> Promote @Fullstop000 to Coprocessor Reviewer

- sig/engine/README.md
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
engine sig: add meeting notes
> engine sig: add meeting notes

- guiding-principles.md
Signed-off-by: WT-Liu <57425373+WT-Liu@users.noreply.github.com>
> add guiding principles 

- sig/transaction/membership.md
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
As title says.
> sig: update Transaction SIG committer member list

- sig/raft/membership.md
Signed-off-by: qupeng <qupeng@pingcap.com>
> add members list for raft sig

- sig/raft/membership.md
Signed-off-by: qupeng <qupeng@pingcap.com>
> update sig/raft committers

- sig/transaction/README.md
- sig/transaction/constitution-zh_CN.md
- sig/transaction/constitution.md
- sig/transaction/membership.md
> sig: refine some info of transaction SIG 

- sig/coprocessor/README.md
Update to use new invitation link
> Update README.md for Coprocessor SIG

- sig/engine/README.md
- sig/performance/README.md
- sig/raft/README.md
- sig/transaction/README.md
This PR updated the link to invite people to join sig's slack channel
Signed-off-by: shirly <AndreMouche@126.com>
> sig/*/README.md: update slack-channels for sig

- GOVERNANCE.md
Signed-off-by: Xintao <hunterlxt@live.com>
> Fix some link error

- sig/transaction/README.md
> Add a link to the sig-transaction repo

- sig/engine/membership.md
Add brson as engine SIG commiter
> Add brson as engine SIG commiter

- sig/scheduling/membership.md
@yisaer has fixed 2 major bugs (https://github.com/tikv/pd/issues/2941 https://github.com/tikv/pd/issues/2783), and reviewed more than 20 PRs.
> sig-scheduling: promote Yisaer to committer

- sig/transaction/README.md
Signed-off-by: andylokandy <andylokandy@hotmail.com>
> Update project links of SIG Transaction

- sig/transaction/README.md
- sig/transaction/constitution.md
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>
> Fix some broken links

- sig/coprocessor/README.md
- sig/coprocessor/charter-zh_CN.md
- sig/coprocessor/charter.md
- sig/engine/README.md
- sig/engine/constitution-zh_CN.md
- sig/scheduling/README.md
- sig/scheduling/constitution-zh_CN.md
- sig/scheduling/constitution.md
- sig/transaction/constitution-zh_CN.md
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>
> Fix broken link

- sig/coprocessor/membership.json
both co tech leaders in cop sig are not even a committer
> remove co-tech leaders for cop sig

- sig/raft/membership.json
Signed-off-by: linning <linningde25@gmail.com>
> Correct member ID

- sig/raft/membership.json
Remove illegal reviewers for raft sig
> remove illegal reviewers for raft sig

- sig/coprocessor/membership.json
> Rename Rustin-Liu to hi-rustin

- sig/coprocessor/membership.json
I'm glad to introduce @Xuanwo to Coprocessor SIG. He's recently made active PRs that merge non-vec/vec coprocessor. Let's welcome the newcomer.
PRs:
- tikv/tikv#4408
- tikv/tikv#8997
- tikv/tikv#8992
- tikv/tikv#8948
- tikv/tikv#8951
- tikv/tikv#8849
- tikv/tikv#8740
- tikv/tikv#8728
> Promote @Xuanwo to Coprocessor active contributor

- sig/coprocessor/README.md
- sig/coprocessor/charter-zh_CN.md
- sig/coprocessor/charter.md
- sig/engine/README.md
- sig/engine/constitution-zh_CN.md
- sig/scheduling/README.md
- sig/scheduling/constitution-zh_CN.md
- sig/scheduling/constitution.md
- sig/transaction/README.md
- sig/transaction/constitution-zh_CN.md
- sig/transaction/constitution.md
> Refine sigs membership link

- sig/transaction/membership.json
> txn: add Fangsong as a reviewer

- sig/transaction/membership.json
PTAL @andylokandy @AndreMouche
> sig-txn: make Ziqian a reviewer

- sig/scheduling/membership.json
Signed-off-by: Song Gao <disxiaofei@163.com>
1. He has filed more than [50+ prs](https://github.com/tikv/pd/issues?q=is%3Apr+author%3AJmPotato+is%3Aclosed) 
2. He participated in the design of local tso and realized it which is a challenging task and he did it quite well.
> Promote committer JmPotato as committer in sig-scheduling

- .github/ISSUE_TEMPLATE/sig-promotion.md
See: https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit
> github: add membership issue template

- .github/labeler.yml
- .github/workflows/ labeler.yml
> github: add labeler

- .github/ISSUE_TEMPLATE/sig-promotion.md
> github: add role to promotion template

- sig/coprocessor/membership.json
> coprocessor: fix wrong name

- sig/coprocessor/membership.json
close https://github.com/pingcap/community/issues/419
> coprocessor: add wshwsh12 to Coprocessor reviewer

- .github/ISSUE_TEMPLATE/sig-promotion.md
> chore: modify the sig promotion assignees

- .github/ISSUE_TEMPLATE/sig-promotion.md
Notify operations staff when an issue is created.
> chore: update the sig promotion assignees

- .github/ISSUE_TEMPLATE/sig-promotion.md
> Revert "chore: update the sig promotion assignees"

- teams/tikv/team.json
followup to #122 . 
sorry I omit this line.
> config: tikv team owns rfcs repo

- teams/raft/team.json
- teams/tikv/team.json
Signed-off-by: tison <wander4096@gmail.com>
> config: accelsao is now jayzhan211

- teams/pd/team.json
wrt. bf88f6d5b41881e70e5bfc01b230b5e5d36a0675
> team: bufferflies as PD committer

- teams/tikv/team.json
- votes/0139-kennytm-as-tikv-committer.md
vote: kennytm as TiKV committer
> vote: kennytm as TiKV committer

- teams/tikv/team.json
- votes/0139-kennytm-as-tikv-committer.md
- votes/0140-marsishandsome-as-tikv-committer.md
Signed-off-by: Andy Lok <andylokandy@hotmail.com>
> vote: marsishandsome as tikv commiter

- votes/TEMPLATE.md
> votes: include deadline for template so that emphasize the minimal length of duration

- teams/tikv/team.json
- votes/0141-gozssky-as-tikv-reviewer.md
> vote: gozssky as TiKV reviwer

- teams/pd/team.json
- votes/0145-busyjay-as-pd-reviewer.md
Signed-off-by: disksing <i@disksing.com>
/cc @BusyJay @nolouch @rleungx
> vote: BusyJay as PD reviewer

- teams/tikv/team.json
- votes/0146-mossaka-as-tikv-reviewer.md
Signed-off-by: Andy Lok <andylokandy@hotmail.com>
/cc @marsishandsome @disksing @iosmanthus @zhongzc @mossaka
> vote: Mossaka as TiKV reviewer

- teams/tikv/team.json
Members in alphabetical order for easily reading. Mentioned at the beginning of the file.
@andylokandy PTAL.
> docs: update team.json in alphabetical order

- GOVERNANCE.md
I joined PingCAP couple month ago. This PR fixes my address and company information.
> Update email address and company

- teams/tikv/team.json
- votes/0159-tier-cap-as-tikv-reviewer.md
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
> vote: tier-cap as TiKV reviwer

- votes/0162-new-pr-requirement-and-commit-message-style.md
Issue Number: ref #161 
@Mini256
> new PR requirement and commit message proposal

- README.md
- teams/tikv/team.json
- votes/0163-pingyu-as-tikv-reviewer.md
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
> vote: prompt pingyu as TiKV reviewer

- votes/0164-tikv-dev-guide.md
Signed-off-by: tison <wander4096@gmail.com>
/cc @tikv/maintainers
> vote: accept TiKV Dev Guide

- GOVERNANCE.md
- votes/0169-zhangyangyu-as-infra-team-member.md
> vote: zhangyangyu as infra team member

- votes/0169-zhangyangyu-as-infra-team-member.md
Signed-off-by: tison <wander4096@gmail.com>
> fix: correct votes result

- teams/prometheus/team.json
- teams/tikv/team.json
Recently I changed my GitHub username from breeswish to breezewish. This PR changes the registry in the community.
> *: update github username for breezewish

- teams/tikv/team.json
- votes/0175-ethercflow-as-tikv-reviewer.md
Signed-off-by: 5kbpers <hustmh@gmail.com>
> vote: ethercflow as TiKV reviwer

- teams/tikv/team.json
- votes/0185-YuJuncen-as-tikv-reviewer.md
> vote: promote YuJuncen as tikv reviewer

- teams/pd/team.json
- votes/0186-CabinfeverB-as-pd-committer.md
Signed-off-by: lhy1024 <admin@liudos.us>
> vote: CabinfeverB as pd comitter

- GOVERNANCE.md
> Nominate dongxu as member of TOC

- GOVERNANCE.md
Refresh the governance document as stated in #207
Closes: #207
> Refresh governance document

- GOVERNANCE.md
> Add Qi Liu as member of TOC

- GOVERNANCE.md
Keep my github id and email updated.
> update github id

- GOVERNANCE.md
> Add Qiu Cui as TOC member

- teams/tikv/team.json
- votes/0226-hhwyt-as-tikv-reviewer.md
#226 has nominated @hhwyt as tikv reviewer but forget to add him to the team member list.
> add hhwyt to tikv reviewers list
